### ISSUE TITLE
Multi Mode error using f311==0.17.10.26.0 or newer

### ISSUE THREAD

**Issue by mike-ivs** [trevisanj/f311#2]
I encountered the following error when using the pfant GUI in multi mode when using a pip version of f311==0.17.10.26.0 or newer. 
```

Traceback (most recent call last):
  File "/XXX/XXX/anaconda2/envs/pyfantenv/lib/python3.6/site-packages/f311/pyfant/gui/a_XMulti.py", line 140, in on_run_multi
    self.__submit_multi()
  File "/XXX/XXX/anaconda2/envs/pyfantenv/lib/python3.6/site-packages/f311/pyfant/gui/a_XMulti.py", line 191, in __submit_multi
    self._rm.add_runnables([r])
  File "/XXX/XXX/anaconda2/envs/pyfantenv/lib/python3.6/site-packages/f311/pyfant/rm.py", line 220, in add_runnables
    self.__unlocked_add_runnables(runnables)
  File "/XXX/XXX/anaconda2/envs/pyfantenv/lib/python3.6/site-packages/f311/pyfant/rm.py", line 382, in __unlocked_add_runnables
    if not runnable.conf.flag_output_to_dir:
AttributeError: 'MultiRunnable' object has no attribute 'conf'
```

I am using the following python script for multi-mode:

```
#  -*- FilePy: FileAbXFwhm -*-

ab = {"Ba" : [-1,0,1,2,3]}

pfant_names = ['Ba-1','Ba0','Ba1','Ba2','Ba3']

conv = [0.12,0.12,1]
```

The script/multi-mode runs correctly using f311==0.17.9.22.0

Best regards,
Mike

**Comment by trevisanj** [comment]
Hi Mike

Thank you for this bug report. I made some fixes and it should work now with f311==0.17.11.22.0

Please note if you use the abundances of "sun-grevesse-2015", you should update the PFANT repository as well, as I had to fix this file, but maybe it is unrelated to your problem.

Regards, Julio
